apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: clusterip-example
  name: livefire
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: clusterip-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clusterip-example
    spec:
      containers:
      - image: livefire-pod:v3
        name: livefire
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
